language: node_js
sudo: true

matrix:
  include:
    - language: android
      dist: trusty
      env: NODEJS_VERSION=16 NDK=r18b BUILD_PLATFORM=android CACHE_NAME=android
      if: NOT tag IS present OR tag !~ /^(daily)/
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'

before_install:
  - wget -q https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
  - sudo unzip -q gradle-5.4.1-bin.zip -d $TRAVIS_HOME/gradle/
  - export PATH=$TRAVIS_HOME/gradle/gradle-5.4.1/bin:$PATH

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew cask uninstall java;
      gem install cocoapods;
      pod setup;
      pod repo update;
      wget -q https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip;
      sudo unzip -q sdk-tools-darwin-4333796.zip -d $TRAVIS_HOME/android-sdk/;
      export ANDROID_HOME=$TRAVIS_HOME/android-sdk;
      sudo chmod -R 777 $ANDROID_HOME;
      wget -q https://dl.google.com/android/repository/android-ndk-${NDK}-darwin-x86_64.zip;
      sudo unzip -q android-ndk-${NDK}-darwin-x86_64.zip -d $TRAVIS_HOME/;
      export ANDROID_NDK_HOME=$TRAVIS_HOME/android-ndk-${NDK};
      export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/tools:$ANDROID_HOME/build-tools:$PATH;
      echo y | sudo sdkmanager "build-tools;28.0.3";
    else
      echo y | sdkmanager "ndk-bundle";
      export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle;
    fi;
  - if [[ $TRAVIS_BRANCH == "release2github" ]]; then
      BUILD_TYPE=release;
      DEPLOY=true;
      BUILD_TYPE_ARG="--release";
    else
      BUILD_TYPE=debug;
      BUILD_TYPE_ARG="";
      if [[ $TRAVIS_BRANCH == "release2github-debug" ]]; then
        DEPLOY=true;
      else
        DEPLOY="";
      fi;
    fi;
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
      .ci_scripts/checkCommit.sh;
      ret=$?;
      if [[ "$ret" -ne 1 ]]; then
        echo "no commit, do not upload apk!";
        DEPLOY="";
      else
        DEPLOY=true;
      fi;
    fi

install:
  - nvm install ${NODEJS_VERSION}
  - npm install -g npm cordova @ionic/cli typescript

script:
  - git branch -vv
  - git submodule foreach 'git branch -vv'
  - if [[ "$DEPLOY" != "" ]]; then
      openssl aes-256-cbc -K $encrypted_7cc824b4064e_key -iv $encrypted_7cc824b4064e_iv -in Elastos-Essentials-release.jks.enc -out Elastos-Essentials-release.jks -d;
      export COMMITID=$(git log --format=%h -1);
      export APPSUFFIX=$(date +'%Y%m%d%H')-$COMMITID;
      export TRAVIS_TAG="daily"-$APPSUFFIX;
      export APPNAME=Essentials-${APPSUFFIX}.apk;
      if [[  $BUILD_TYPE != "release" ]]; then
        sed -i "s/ version=\"[0-9d.]*/&.${COMMITID}/" $TRAVIS_BUILD_DIR/App/config.xml;
      fi;
    fi
  - export APK_PATH=$TRAVIS_BUILD_DIR/App/platforms/android/app/build/outputs/apk/$BUILD_TYPE
  - $TRAVIS_BUILD_DIR/ToolChains/bin/build all -pf $BUILD_PLATFORM --build $BUILD_TYPE_ARG
  - ls -l $APK_PATH

after_success:
  - if [[ "$DEPLOY" != "" ]]; then
      cd $TRAVIS_BUILD_DIR/App;
      cordova build android --$BUILD_TYPE -- --keystore="../Elastos-Essentials-release.jks" --storePassword=$storepass --password=$storepass --alias=key0;
      cd $APK_PATH;
      cp app-${BUILD_TYPE}.apk $APPNAME;
      ls -l;
    fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  # timeout: 1000
  cocoapods: true
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.cocoapods/

notifications:
  email:
  - raozhiming@trinity-tech.io
  - benjaminpiette@elastos-fusion.org

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $USER_NAME
  - git config --local user.email $USER_EMAIL
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: Essentials*.apk
  skip_cleanup: true
  prerelease: true
  on:
    condition: $DEPLOY != ""
    all_branches: true

env:
  global:
  - secure: iirP58whyuJHukzqSzNNTpRco8r6qRR8M/ZtRD8PB49ZuU+4c+x1TFIQJ0KzGo6C9QaXc+vWkQv2NtDM7Lz9chKPWDQE1R/msjvQ/qfeFwkzzMAeGhejimnTRFyikJa9u+qX9F0O18/GGPFWmxRVamC+7zM/9xmX67iOzrUHj82lHw7P5Uyc9DZvI1XNUOpd0KanGRE7THA79z0I5XmNNpgCJcd+s7bqQeHUGMMwYGNGOSo2ibo4/Av4UUR1Jnr5kFvQ9om4G/AgPNLik9x9fhGAHjjUTrI7YAU8feXRMySXxdXD8eoLUkKm0/4DbQYTypWuqgD4JehwMrSriRBUwvKnObX1Q2SP/87xGvUFlxgjTj8EoCQVI8YazTEIgSoN6LA92SdSYQlej4ZQh9OKj59Xvpxky1A5HBJyU++qlPUFjYa7pBOLeV4Aq2jbdP+0UCRA6AEuFHSVu/Wl7oZmg43yN1AeeY8t9jwKODe1guFVARdCARKOR1vMfFHqXw5nD06OUPrXgySZTfFLVm8UUqS/NCLvGMMVS984lH/MQqyxNrjgwaDbrzMt1V9947YFmnDc1q2C8zNHWHwYwr1WFJsbSk72WTaYoZTQXWnhOsaDc10pIYeFTmiQknvyMCztzgAVgn8k9gJD/LZYyLH6+2v7Rdavh2Kg/EN41kem6BQ=
